Hw 27 03
pavlo-ilkanych/java_core_basics pull request #15
Opened 2021-03-27 17:14 UTC by pavlo-ilkanych

Кожен коміт то окреме завдання домашки, всього 4 коміти.

2021-03-27 19:24 UTC, ValentinTyhonov requested changes
Всі завдання зроблені норм, але до класу Methods можна і причепитися)
1. Використовуй try-with-resources для створення об'єктів класів InputStream, OutputStream і їх нащадків. Тоді ресурси будуть автоматично закриті, викликаний метод close(), вкінці виконання твого методу.
2. Коли ти вже не використовуєш об'єкти класів InputStream, OutputStream і їх нащадків, то їх обов'язково потрібно закрити (викликати метод close(). Тут ти закрив лише один об'єкт - objectOutputStream. Щоб закрити ті ресурси, використовуєш try-with-resources, або try-catch-finally і у блоці finally викликаєш метод close(). Інакше, якщо випаде екзепшин, ресурси можуть залишитися незакритими.
3. Логічніше, якби метод serialize приймав ще шлях до файлу, тоді він був би більш гнучким.
4. Метод deserialize мав би повертати тоді той десереалізований об'єкт, а приймати лише шлях до файлу.
5. (Object) objectInputStream.readObject() - це не має сенсу. Метод readObject() повертає Object, отже явне приведення типів непотрібне.
6. Є два варіанти як поступити з методом deserialize:
  - метод повертає Object і вже в Main ти приводиш тип явно до Employee при виклиці методу deserialize;
  - тип повернення метода є Generic і ти робиш явне приведення всередині deserialize і дозволяєш людям, які користуватимуться твоїм методом не паритися щодо приведення типів.

2021-03-28 10:23 UTC, pavlo-ilkanych commented
На рахунок методу deserialize. Ще його можна зробити так, незнаю чи є якась різниця, бо працює і так і так.
public  <K> K deserialize(String path){

        Object obj = null;  // було "K obj = null;"
        try (FileInputStream fileInputStream = new FileInputStream(path);
        ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream))
        {
            obj = objectInputStream.readObject(); //тут відбувалося явне приведення "(К)"
            System.out.println(obj);
        }catch (IOException | ClassNotFoundException e) {
            System.err.println(e.getMessage());
        }
        return (K) obj;  // тут вертали просто "obj"
    }

2021-03-28 13:13 UTC, ValentinTyhonov commented
Так і так норм. Тільки було б добре, якби ти ще й використав в мейні те, що повертає метод deserialize. 
`    public static void main(String[] args) throws IOException, ClassNotFoundException {

        String path = "src/com/company/task/store";

        Methods methods = new Methods();
        Employee employee = new Employee("Jack", 123456, new Salary(1000));

        methods.serialize(employee, path);
        Employee employeeRestored = methods.deserialize(path);

        System.out.println(employeeRestored);

        Collection<Employee> collection = new ArrayList<>();

        collection.add(employee);
        collection.add(new Employee("John", 147258, new Salary(1500)));

        methods.serialize(collection, path);
        Collection<Employee> collectionRestored = methods.deserialize(path);

        System.out.println(collectionRestored);
    }`

2021-03-28 13:15 UTC, ValentinTyhonov commented
тв й методи в класі Methods цілком можуть бути статичними.

2021-03-28 13:45 UTC, pavlo-ilkanych commented
Зробив.

2021-03-28 13:51 UTC, ValentinTyhonov approved these changes
а. і забув сказати. клас Method не повинен імплементувати інтерфейс Serializable. Там нема чого сереалізувати.

2021-03-28 17:41 UTC, ValentinTyhonov approved these changes

2021-03-28 17:41 UTC, merged